name: "🙏 ​ ​Submit a Project Idea"
description: Help us add project ideas to roadmaps.
labels: [project contribution]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a project idea! Please fill out the information below and we'll get back to you as soon as we can.
  - type: input
    id: roadmap-title
    attributes:
      label: What Roadmap is this project for?
      placeholder: e.g. Backend Roadmap
    validations:
      required: true
  - type: dropdown
    id: project-difficulty
    attributes:
      label: Project Difficulty
      options:
        - Beginner
        - Intermediate
        - Advanced
    validations:
      required: true
  - type: textarea
    id: roadmap-description
    attributes:
      label: Add Project Details
      description: Please write a detailed description of the project in 3rd person e.g. "You are required to build a..."
      placeholder: |
          e.g. You are required to build a RESTful API...
    validations:
      required: true
